import { Item } from './Item';
import { CrystalBall } from './BasicItems/CrystalBall';
import { SobiMask } from './BasicItems/SobiMask';
import { MoonArmor } from './BasicItems/MoonArmor';
import { IronShield } from './BasicItems/IronShield';
import { ReinforcedHide } from './BasicItems/ReinforcedHide';
import { StuddedLeatherArmor } from './BasicItems/StuddedLeatherArmor';
import { BootsOfSpeed } from './BasicItems/BootsOfSpeed';
import { BloodiedExecutionersAxe } from './BasicItems/BloodiedExecutionersAxe';
import { BlueSoulstone } from './BasicItems/BlueSoulstone';
import { DruidicSalve } from './BasicItems/DruidicSalve';
import { Claws } from './BasicItems/Claws';
import { CloakOfShadows } from './BasicItems/CloakOfShadows';
import { ClockworkPenguin } from './BasicItems/ClockworkPenguin';
import { EmptySoulcage } from './BasicItems/EmptySoulcage';
import { EmptyVial } from './BasicItems/EmptyVial';
import { FlareGun } from './BasicItems/FlareGun';
import { GoblinBattery } from './BasicItems/GoblinBattery';
import { GreenSoulstone } from './BasicItems/GreenSoulstone';
import { IronSword } from './BasicItems/IronSword';
import { OrbOfMagic } from './BasicItems/OrbOfMagic';
import { PurpleSoulstone } from './BasicItems/PurpleSoulstone';
import { Scepter } from './BasicItems/Scepter';
import { WarAxe } from './BasicItems/WarAxe';
import { RunedBracers } from './BasicItems/RunedBracers';
import { GoblinNightScope } from './BasicItems/GoblinNightScope';
import { BloodiedSacrificialDagger } from './BasicItems/BloodiedSacrificialDagger';
import { VampireClaws } from './BasicItems/VampireClaws';
import { JuggernautArmor } from './BasicItems/JuggernautArmor';
import { EnchantedGemstone } from './BasicItems/EnchantedGemstone';
import { OrbOfLightning } from './BasicItems/OrbOfLightning';
import { IronwoodBranch } from './BasicItems/IronwoodBranch';
import { AmuletOfSpellReflection } from './BasicItems/AmuletOfSpellReflection';
import { AssassinsMap } from './BasicItems/AssassinsMap';
import { LifeStone } from './BasicItems/LifeStone';
import { SteelSpear } from './BasicItems/SteelSpear';
import { PipeOfInsight } from './BasicItems/PipeOfInsight';
import { FairyWand } from './BasicItems/FairyWand';
import { OrbOfFire } from './BasicItems/OrbOfFire';
import { AssassinsBlade } from './BasicItems/AssassinsBlade';
import { SpiritTalisman } from './BasicItems/SpiritTalisman';

export const itemMap: Map<string, Item> = new Map();

itemMap.set('crystalBall', new CrystalBall());
itemMap.set('sobiMask', new SobiMask());
itemMap.set('moonArmor', new MoonArmor());
itemMap.set('ironShield', new IronShield());
itemMap.set('reinforcedHide', new ReinforcedHide());
itemMap.set('studdedLeatherArmor', new StuddedLeatherArmor());
itemMap.set('bootsOfSpeed', new BootsOfSpeed());
itemMap.set('bloodiedExecutionersAxe', new BloodiedExecutionersAxe());
itemMap.set('blueSoulstone', new BlueSoulstone());
itemMap.set('druidicSalve', new DruidicSalve());
itemMap.set('claws', new Claws());
itemMap.set('cloakOfShadows', new CloakOfShadows());
itemMap.set('clockworkPenguin', new ClockworkPenguin());
itemMap.set('emptySoulcage', new EmptySoulcage());
itemMap.set('emptyVial', new EmptyVial());
itemMap.set('flareGun', new FlareGun());
itemMap.set('goblinBattery', new GoblinBattery());
itemMap.set('greenSoulstone', new GreenSoulstone());
itemMap.set('ironSword', new IronSword());
itemMap.set('orbOfMagic', new OrbOfMagic());
itemMap.set('purpleSoulstone', new PurpleSoulstone());
itemMap.set('scepter', new Scepter());
itemMap.set('warAxe', new WarAxe());
itemMap.set('runedBracers', new RunedBracers());
itemMap.set('goblinNightScope', new GoblinNightScope());
itemMap.set('bloodiedSacrificialDagger', new BloodiedSacrificialDagger());
itemMap.set('vampireClaws', new VampireClaws());
itemMap.set('spiritTalisman', new SpiritTalisman());
itemMap.set('juggernautArmor', new JuggernautArmor());
itemMap.set('enchantedGemstone', new EnchantedGemstone());
itemMap.set('orbOfLightning', new OrbOfLightning());
itemMap.set('ironwoodBranch', new IronwoodBranch());
itemMap.set('amuletOfSpellReflection', new AmuletOfSpellReflection());
itemMap.set('assassinsMap', new AssassinsMap());
itemMap.set('lifeStone', new LifeStone());
itemMap.set('steelSpear', new SteelSpear());
itemMap.set('pipeOfInsight', new PipeOfInsight());
itemMap.set('fairyWand', new FairyWand());
itemMap.set('orbOfFire', new OrbOfFire());
itemMap.set('assassinsBlade', new AssassinsBlade());

export const basicItems: Item[] = [...itemMap.values()] as Item[];
